1.204 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/scripts/close-release b/debian/scripts/close-release
--- a/debian/scripts/close-release
+++ b/debian/scripts/close-release
@@ -3,11 +3,48 @@
 # Close a release
 #
 
+function usage()
+{
+	cat <<EOF
+Usage: $(basename "${0}") [-h] [VERSION]
+
+Create a release commit.
+
+Positional arguments:
+  VERSION     The new package version. If not provided, increments the current
+              version by one.
+
+Optional arguments:
+  -h, --help  Show this help text and exit.
+EOF
+}
+
+new_version=
+
+while [ ${#} -gt 0 ] ; do
+	case "${1}" in
+		-h|--help)
+			usage
+			exit
+			;;
+		*)
+			if [ -n "${new_version}" ] ; then
+				echo "Invalid argument: ${1}" >&2
+				exit 2
+			fi
+			new_version=${1}
+			;;
+	esac
+	shift
+done
+
 release=$(dpkg-parsechangelog -SDistribution)
 version=$(dpkg-parsechangelog -SVersion)
 
 # The version and tag of the new release
-new_version="${version%.*}.$((${version##*.} + 1))"
+if [ -z "${new_version}" ] ; then
+	new_version="${version%.*}.$((${version##*.} + 1))"
+fi
 new_tag="Ubuntu-${new_version}"
 
 # Check if the tag exists already
@@ -35,6 +72,32 @@ fi
 	while IFS= read -r line ; do
 		commit=${line%% *}
 		subject=${line#* }
+
+		# Parse the commit message for Ignores and BugLinks
+		ignore=0
+		bugs=""
+		while IFS= read -r line ; do
+			case "${line,,}" in
+				"ignore: yes")
+					ignore=1
+					;;
+				"buglink: https://bugs.launchpad.net/bugs/"*)
+					bug="LP: #${line##*/}"
+					bugs="${bugs}, ${bug}"
+					;;
+			esac
+		done < <(git log --format=%b "${commit}" -1)
+
+		if [ ${ignore} -eq 1 ] ; then
+			# Ignore commits with 'Ignore: yes'
+			continue
+		fi
+
+		if [ -n "${bugs}" ] ; then
+			# Add bugs to the changelog
+			subject="${subject} (${bugs:2})"
+		fi
+
 		# shellcheck disable=SC2001
 		subject=$(echo "${subject}" | sed 's,\s*UBUNTU:\s*,,')
 
@@ -54,6 +117,6 @@ fi
 } > debian/changelog.new
 mv debian/changelog.new debian/changelog
 
-# Commit and tag the new release
+# Commit the new release
 git commit -s -m "UBUNTU: ${new_tag}" -- debian/changelog
-git tag -s -m  "UBUNTU: ${new_tag}" "${new_tag}"
+debian/scripts/tag-release
